---

dependencies: []

galaxy_info:
  author: igor.mukhin@gmail.com
  description: Ansible role to install clamav antivirus and optionally ClamTK
  license: MIT
  min_ansible_version: 1.4
  platforms:
  - name: Ubuntu
    versions:
    - precise
    # - quantal

    # - raring
    # - saucy

    - trusty
    # - utopic

  - name: Debian
    versions:
    - all
  categories:
    - system
